// Asset pipeline (placeholder kit). Authors a small building kit from scratch, optimizes it with
// gltf-transform (weld → dedup → prune → meshopt compression), writes hashed .glb files to
// public/kits/, and emits manifest.json. This PROVES the Blender→web pipeline end-to-end; real
// authored .glb modules drop into public/kits-src/ later and reuse the same optimize+manifest path.
//
//   npm run assets
//
// Module convention: footprint normalized to 1×1 in XZ (centred), built upward from y=0 to `height`
// metres, +Y up. Placement scales X/Z by the building's width/depth and stacks ground+mids+roof.
import { Document, NodeIO } from '@gltf-transform/core';
import { EXTMeshoptCompression } from '@gltf-transform/extensions';
import { weld, dedup, prune } from '@gltf-transform/functions';
import { MeshoptEncoder } from 'meshoptimizer';
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync, renameSync, readdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'public', 'kits');

// ---- tiny box-soup geometry builder (non-indexed; weld dedups on optimize) ----
function boxSoup(boxes) {
  const P = [], N = [];
  for (const { x = 0, y = 0, z = 0, w, h, d } of boxes) {
    const hx = w / 2, hz = d / 2; // X/Z centred; Y spans [y, y+h]
    const v = [
      [-hx, y, -hz], [hx, y, -hz], [hx, y + h, -hz], [-hx, y + h, -hz],
      [-hx, y, hz], [hx, y, hz], [hx, y + h, hz], [-hx, y + h, hz],
    ].map(([a, b, c]) => [a + x, b, c + z]);
    const faces = [
      [0, 2, 1, [0, 0, -1]], [0, 3, 2, [0, 0, -1]],
      [5, 7, 4, [0, 0, 1]], [5, 6, 7, [0, 0, 1]],
      [4, 3, 0, [-1, 0, 0]], [4, 7, 3, [-1, 0, 0]],
      [1, 6, 5, [1, 0, 0]], [1, 2, 6, [1, 0, 0]],
      [3, 6, 2, [0, 1, 0]], [3, 7, 6, [0, 1, 0]],
      [4, 1, 5, [0, -1, 0]], [4, 0, 1, [0, -1, 0]],
    ];
    for (const [a, b, c, nm] of faces) {
      for (const idx of [a, b, c]) { P.push(...v[idx]); N.push(...nm); }
    }
  }
  return { pos: new Float32Array(P), nrm: new Float32Array(N) };
}

// Module silhouettes — deliberately "modelled" (ledges/bands/parapet) so they read as authored,
// not plain boxes. Footprint within ±0.5 (1×1). Heights in metres.
const MODULES = {
  bld_z1_ground: { height: 4, boxes: [
    { y: 0, w: 1.0, h: 4, d: 1.0 },               // shaft
    { y: 0, w: 1.06, h: 0.5, d: 1.06 },           // base ledge
    { y: 3.7, w: 1.04, h: 0.3, d: 1.04 },         // floor slab
  ]},
  bld_z1_mid_a: { height: 3.5, boxes: [
    { y: 0, w: 0.96, h: 3.5, d: 0.96 },           // inset shaft (window band reads as the gap)
    { y: 3.2, w: 1.02, h: 0.3, d: 1.02 },         // floor slab band
  ]},
  bld_z1_mid_b: { height: 3.5, boxes: [
    { y: 0, w: 0.98, h: 3.5, d: 0.92 },           // a differently-proportioned variant
    { y: 3.2, w: 1.02, h: 0.3, d: 1.0 },
  ]},
  bld_z1_roof: { height: 3, boxes: [
    { y: 0, w: 1.0, h: 2.2, d: 1.0 },             // top floor
    { y: 2.2, w: 1.04, h: 0.4, d: 1.04 },         // parapet
    { x: 0.18, z: -0.15, y: 2.6, w: 0.4, h: 0.4, d: 0.4 }, // rooftop mechanical
  ]},
};

await MeshoptEncoder.ready;
const io = new NodeIO().registerExtensions([EXTMeshoptCompression])
  .registerDependencies({ 'meshopt.encoder': MeshoptEncoder });

mkdirSync(outDir, { recursive: true });
for (const f of readdirSync(outDir)) rmSync(join(outDir, f)); // clean stale hashed files

const manifest = { note: 'Generated by tools/build-kit.mjs — do not hand-edit.', kits: { z1: { ground: null, mid: [], roof: null } } };

for (const [id, def] of Object.entries(MODULES)) {
  const doc = new Document();
  const buffer = doc.createBuffer();
  const { pos, nrm } = boxSoup(def.boxes);
  const position = doc.createAccessor().setType('VEC3').setArray(pos).setBuffer(buffer);
  const normal = doc.createAccessor().setType('VEC3').setArray(nrm).setBuffer(buffer);
  const mat = doc.createMaterial(id).setRoughnessFactor(0.8).setMetallicFactor(0.05)
    .setBaseColorFactor([0.55, 0.58, 0.66, 1]);
  const prim = doc.createPrimitive().setAttribute('POSITION', position).setAttribute('NORMAL', normal).setMaterial(mat);
  const mesh = doc.createMesh(id).addPrimitive(prim);
  doc.createScene().addChild(doc.createNode(id).setMesh(mesh));

  await doc.transform(weld(), dedup(), prune());
  // meshopt-compress geometry (EXT_meshopt_compression) — faster decode than Draco, one decoder.
  doc.createExtension(EXTMeshoptCompression).setRequired(true)
    .setEncoderOptions({ method: EXTMeshoptCompression.EncoderMethod.QUANTIZE });

  const glb = await io.writeBinary(doc);
  const hash = createHash('sha1').update(glb).digest('hex').slice(0, 8);
  const file = `${id}.${hash}.glb`;
  writeFileSync(join(outDir, file), Buffer.from(glb));

  const entry = { id, url: `kits/${file}`, height: def.height };
  if (id === 'bld_z1_ground') manifest.kits.z1.ground = entry;
  else if (id === 'bld_z1_roof') manifest.kits.z1.roof = entry;
  else manifest.kits.z1.mid.push(entry);
  console.log(`  ${file}  (${glb.byteLength} bytes)`);
}

writeFileSync(join(outDir, 'manifest.json'), JSON.stringify(manifest, null, 2));
console.log('wrote manifest.json — z1 kit: ground + ' + manifest.kits.z1.mid.length + ' mid variants + roof');
